// @ts-nocheck
"use client";
import { useEffect, useRef, useState } from "react";
import { useFrame, type ThreeEvent } from "@react-three/fiber";
import {
  useGLTF,
  useTexture,
  // OrbitControls,
} from "@react-three/drei";
import { type Group, MathUtils } from "three";
import { animated } from "@react-spring/three";

// Add type declarations for the MacBookModel props
interface MacBookModelProps {
  open: boolean;
  hinge: number;
  [key: string]: any;
}

function MacBookModel({ open, hinge, ...props }: MacBookModelProps) {
  const group = useRef<Group>(null);
  // Load model
  const { nodes, materials } = useGLTF("/assets/models/mac-draco.glb");

  const monitorTexture0 = useTexture("/assets/images/desktop0.webp");
  const monitorTexture1 = useTexture("/assets/images/desktop1.webp");
  const monitorTexture2 = useTexture("/assets/images/desktop2.webp");

  monitorTexture0.flipY = false;
  monitorTexture1.flipY = false;
  monitorTexture2.flipY = false;

  const [bg, setBg] = useState(monitorTexture1);

  // Take care of cursor state on hover
  const [hovered, setHovered] = useState(false);
  useEffect(() => {
    document.body.style.cursor = hovered ? "pointer" : "auto";
  }, [hovered]);

  useEffect(() => {
    const bgs = [monitorTexture0, monitorTexture1, monitorTexture2];
    let count = 0;
    const id = setInterval(() => {
      count += 1;
      if (count === 3) {
        count = 0;
      }
      setBg(bgs[count]);
    }, 5000);

    return () => {
      clearInterval(id);
    };
  }, []);

  // Make it float in the air when it's opened
  useFrame((state) => {
    if (!group.current) return;
    const t = state.clock.getElapsedTime();
    group.current.rotation.x = MathUtils.lerp(group.current.rotation.x, open ? Math.cos(t / 10) / 10 + 0.25 : 0, 0.1);
    group.current.rotation.y = MathUtils.lerp(group.current.rotation.y, open ? Math.sin(t / 10) / 6 : 0, 0.1);
    group.current.rotation.z = MathUtils.lerp(group.current.rotation.z, open ? Math.sin(t / 10) / 30 : 0, 0.1);

    group.current.position.y = MathUtils.lerp(group.current.position.y, open ? (-2 + Math.sin(t)) / 3 : -4.3, 0.1);
  });

  // The view was auto-generated by: https://github.com/pmndrs/gltfjsx
  // Events and spring animations were added afterwards

  return (
    <group
      ref={group}
      {...props}
      onPointerOver={(e: ThreeEvent<PointerEvent>) => (e.stopPropagation(), setHovered(true))}
      onPointerOut={() => setHovered(false)}
      dispose={null}
    >
      <animated.group rotation-x={hinge} position={[0, -0.04, 0.41]}>
        <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials.aluminium} geometry={nodes["Cube008"].geometry} />
          <mesh material={materials["matte.001"]} geometry={nodes["Cube008_1"].geometry} />
          <mesh material={materials["screen.001"]} geometry={nodes["Cube008_2"].geometry}>
            <meshMatcapMaterial map={bg} />
          </mesh>
        </group>
      </animated.group>
      <mesh material={materials.keys} geometry={nodes.keyboard.geometry} position={[1.79, 0, 3.45]} />
      <group position={[0, -0.1, 3.39]}>
        <mesh material={materials.aluminium} geometry={nodes["Cube002"].geometry} />
        <mesh material={materials.trackpad} geometry={nodes["Cube002_1"].geometry} />
      </group>
      <mesh material={materials.touchbar} geometry={nodes.touchbar.geometry} position={[0, -0.03, 1.2]} />
    </group>
  );
}

export default MacBookModel;
