/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 letter-Y.glb -T 
Files: letter-Y.glb [42.04KB] > /Users/yilong/Code/Personal/yilong-portfolio-site/public/assets/models/letter-Y-transformed.glb [8.6KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/letter-Y-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Capsule.geometry} material={nodes.Capsule.material} position={[0, -1.095, 0]} />
    </group>
  )
}

useGLTF.preload('/letter-Y-transformed.glb')
