/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot_2.glb -T
Files: robot_2.glb [25.4MB] > /Users/yilong/Code/Personal/yilong-portfolio-site/public/assets/models/robot_2-transformed.glb [2.09MB] (92%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/robot_2-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
        </group>
        <skinnedMesh
          name="mask"
          geometry={nodes.mask.geometry}
          material={materials["Transparency_shader.001"]}
          skeleton={nodes.mask.skeleton}
        />
        <group name="shoulder001">
          <skinnedMesh
            name="Mesh_13001"
            geometry={nodes.Mesh_13001.geometry}
            material={materials["Main_shader.001"]}
            skeleton={nodes.Mesh_13001.skeleton}
          />
          <skinnedMesh
            name="Mesh_13001_1"
            geometry={nodes.Mesh_13001_1.geometry}
            material={materials["Transparency_shader.001"]}
            skeleton={nodes.Mesh_13001_1.skeleton}
          />
          <skinnedMesh
            name="Mesh_13001_2"
            geometry={nodes.Mesh_13001_2.geometry}
            material={materials["Hand_proxy_shader.001"]}
            skeleton={nodes.Mesh_13001_2.skeleton}
          />
          <skinnedMesh
            name="Mesh_13001_3"
            geometry={nodes.Mesh_13001_3.geometry}
            material={materials["Insides_shader.001"]}
            skeleton={nodes.Mesh_13001_3.skeleton}
          />
        </group>
        <skinnedMesh
          name="柱体004"
          geometry={nodes.柱体004.geometry}
          material={nodes.柱体004.material}
          skeleton={nodes.柱体004.skeleton}
        />
        <skinnedMesh
          name="柱体005"
          geometry={nodes.柱体005.geometry}
          material={nodes.柱体005.material}
          skeleton={nodes.柱体005.skeleton}
        />
        <skinnedMesh
          name="柱体006"
          geometry={nodes.柱体006.geometry}
          material={nodes.柱体006.material}
          skeleton={nodes.柱体006.skeleton}
        />
        <skinnedMesh
          name="柱体007"
          geometry={nodes.柱体007.geometry}
          material={nodes.柱体007.material}
          skeleton={nodes.柱体007.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/robot_2-transformed.glb");
