/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.glb -T
Files: robot.glb [5.14MB] > /Users/yilong/Code/Personal/yilong-portfolio-site/public/assets/models/robot-transformed.glb [613.44KB] (88%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/robot-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.baked} position={[0, 1.436, 0.039]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.lidar} position={[0, 1.41, 0.027]} scale={0.027} />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.material}
        position={[0, 1.436, 0.039]}
        scale={[0.033, 0.039, 0.039]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials["Material.001"]}
        position={[0.312, 0.793, 0.016]}
        scale={0.019}
      />
    </group>
  );
}

useGLTF.preload("/robot-transformed.glb");
