/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 letter-H.glb -T
Files: letter-H.glb [62.55KB] > /Users/yilong/Code/Personal/yilong-portfolio-site/public/assets/models/letter-H-transformed.glb [8.01KB] (87%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/assets/models/letter-H-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Capsule.geometry} material={nodes.Capsule.material} position={[-2, 0, 0]} />
    </group>
  );
}

useGLTF.preload("/assets/models/letter-H-transformed.glb");
