"use client";

// React Three Fiber for React integration with Three.js
import { Canvas } from "@react-three/fiber";
// Drei library for pre-built 3D components and utilities
import { useGLTF, Environment, Lightformer } from "@react-three/drei";
// Post-processing effects for enhanced visual quality
import { EffectComposer, N8AO } from "@react-three/postprocessing";
// Math utilities for smooth animations and transitions

// Main component that wraps the 3D scene in a styled container
export default function BasicUnitree() {
  return (
    <section className="mx-auto h-[800px] w-full max-w-3xl">
      <RobotScene />
    </section>
  );
}

// Main 3D scene component that sets up the Canvas and all 3D elements
function RobotScene(props) {
  return (
    <Canvas
      shadows // Enable shadow rendering
      dpr={[1, 2]} // Device pixel ratio for crisp rendering
      gl={{ antialias: false }} // Disable antialiasing for performance
      camera={{ position: [0, 1, 5], fov: 8, near: 1, far: 30 }} // Camera setup
      {...props}
    >
      {/* Background color - dark blue-gray */}
      <color attach="background" args={["#334"]} />

      {/* Ambient light for overall scene illumination */}
      <ambientLight intensity={2} />

      {/* Spotlight for dramatic lighting and shadows */}
      <spotLight position={[10, 10, 10]} angle={0.5} penumbra={1} intensity={8} castShadow />

      <Model position={[0, -1.2, 0]} rotation={[0, -0.3, 0]} />

      {/* Post-processing effects for enhanced visual quality */}
      <EffectComposer disableNormalPass multisampling={8}>
        {/* Ambient occlusion for realistic shadowing */}
        <N8AO distanceFalloff={1} aoRadius={1} intensity={4} />
      </EffectComposer>

      {/* Environment lighting setup with multiple light sources */}
      <Environment resolution={256}>
        <group rotation={[-Math.PI / 3, 0, 1]}>
          {/* Various lightformers positioned around the scene for realistic lighting */}
          <Lightformer form="circle" intensity={8} rotation-x={Math.PI / 2} position={[0, 5, -9]} scale={2} />
          <Lightformer form="circle" intensity={8} rotation-y={Math.PI / 2} position={[-5, 1, -1]} scale={2} />
          <Lightformer form="circle" intensity={8} rotation-y={Math.PI / 2} position={[-5, -1, -1]} scale={2} />
          <Lightformer form="circle" intensity={8} rotation-y={-Math.PI / 2} position={[10, 1, 0]} scale={8} />
        </group>
      </Environment>
    </Canvas>
  );
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.glb -T
Files: robot.glb [5.14MB] > /Users/yilong/Code/Personal/yilong-portfolio-site/public/assets/models/robot-transformed.glb [613.44KB] (88%)
*/

export function Model(props) {
  const { nodes, materials } = useGLTF("/assets/models/robot-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.baked} position={[0, 1.436, 0.039]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.lidar} position={[0, 1.41, 0.027]} scale={0.027} />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.material}
        position={[0, 1.436, 0.039]}
        scale={[0.033, 0.039, 0.039]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials["Material.001"]}
        position={[0.312, 0.793, 0.016]}
        scale={0.019}
      />
    </group>
  );
}

// useGLTF.preload("/assets/models/robot-transformed.glb");
