/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -t -T
Files: model.glb [25.4MB] > public/assets/models/robot/model-transformed.glb [2.09MB] (92%)
*/

import type { AnimationClip, Group, SkinnedMesh, Bone, MeshStandardMaterial } from "three";
import { type ComponentProps, useEffect, useMemo, useRef, useState } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { type GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "idle";

interface GLTFAction extends AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    mask: SkinnedMesh;
    Mesh_13001: SkinnedMesh;
    Mesh_13001_1: SkinnedMesh;
    Mesh_13001_2: SkinnedMesh;
    Mesh_13001_3: SkinnedMesh;
    mixamorigHips: Bone;
    Ctrl_Master: Bone;
    Ctrl_ArmPole_IK_Left: Bone;
    Ctrl_Hand_IK_Left: Bone;
    Ctrl_ArmPole_IK_Right: Bone;
    Ctrl_Hand_IK_Right: Bone;
    Ctrl_Foot_IK_Left: Bone;
    Ctrl_LegPole_IK_Left: Bone;
    Ctrl_Foot_IK_Right: Bone;
    Ctrl_LegPole_IK_Right: Bone;
  };
  materials: {
    ["Transparency_shader.001"]: MeshStandardMaterial;
    ["Main_shader.001"]: MeshStandardMaterial;
    ["Hand_proxy_shader.001"]: MeshStandardMaterial;
    ["Insides_shader.001"]: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: ComponentProps<"group"> & { onLoadComplete: () => void }) {
  const group = useRef<Group | null>(null);
  const [isLoaded, setIsLoaded] = useState(false);
  // const { scene, animations } = useGLTF("/assets/models/robot/gltf/model.gltf");
  const { scene, animations } = useGLTF("/assets/models/robot/model-optimized.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  const { onLoadComplete } = props;

  useEffect(() => {
    if (scene && !isLoaded) {
      setIsLoaded(true);
      onLoadComplete?.();
    }
  }, [scene, isLoaded, onLoadComplete]);

  useEffect(() => {
    if (isLoaded && actions["idle"]) {
      // actions["idle"].reset().fadeIn(1.5).play();
      actions["idle"].play();
    }
  }, [actions, isLoaded]);

  console.log(" --= Render Robot Model =-- ");

  return (
    <group ref={group} scale={0.02} position={[0, -2.8, 0]} dispose={null}>
      {/* <group ref={group} {...props} dispose={null}> */}
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
        </group>
        <skinnedMesh
          name="mask"
          geometry={nodes.mask.geometry}
          material={materials["Transparency_shader.001"]}
          skeleton={nodes.mask.skeleton}
        />
        <group name="shoulder001">
          <skinnedMesh
            name="Mesh_13001"
            geometry={nodes.Mesh_13001.geometry}
            material={materials["Main_shader.001"]}
            skeleton={nodes.Mesh_13001.skeleton}
          />
          <skinnedMesh
            name="Mesh_13001_1"
            geometry={nodes.Mesh_13001_1.geometry}
            material={materials["Transparency_shader.001"]}
            skeleton={nodes.Mesh_13001_1.skeleton}
          />
          <skinnedMesh
            name="Mesh_13001_2"
            geometry={nodes.Mesh_13001_2.geometry}
            material={materials["Hand_proxy_shader.001"]}
            skeleton={nodes.Mesh_13001_2.skeleton}
          />
          <skinnedMesh
            name="Mesh_13001_3"
            geometry={nodes.Mesh_13001_3.geometry}
            material={materials["Insides_shader.001"]}
            skeleton={nodes.Mesh_13001_3.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/assets/models/robot/gltf/model.gltf");
useGLTF.preload("/assets/models/robot/model-optimized.glb");
