name: Cypress E2E Tests on Chrome

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Cypress run
        uses: cypress-io/github-action@v6
        # env:
        #   CYPRESS_BASE_URL: http://localhost:3000
        with:
          component: true
          build: yarn build
          start: yarn start
          command: yarn test:ci
          browser: chrome
          wait-on: "http://localhost:3000"
